# Generated by Django 3.0.5 on 2021-01-06 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rooms', models.IntegerField()),
                ('area', models.FloatField()),
                ('floor', models.IntegerField()),
                ('year', models.IntegerField()),
                ('bathrooms', models.IntegerField()),
                ('kitchens', models.IntegerField()),
                ('link', models.URLField(blank=True)),
                ('zone', models.CharField(max_length=255)),
                ('price', models.FloatField()),
            ],
        ),
    ]
