// This file was auto-generated by ML.NET Model Builder. 

using Microsoft.ML.Data;

namespace MLAPI.DataModels
{
    public class PropertyPrediction
    {
        [ColumnName("Score")]
        public float Score { get; set; }
    }
}
