// This file was auto-generated by ML.NET Model Builder. 

using Microsoft.ML.Data;

namespace MLAPI.DataModels
{
    public class PropertyData
    {
        [ColumnName("rooms"), LoadColumn(0)]
        public float Rooms { get; set; }


        [ColumnName("area"), LoadColumn(1)]
        public float Area { get; set; }


        [ColumnName("floor"), LoadColumn(2)]
        public float Floor { get; set; }


        [ColumnName("year"), LoadColumn(3)]
        public float Year { get; set; }


        [ColumnName("bathrooms"), LoadColumn(4)]
        public float Bathrooms { get; set; }


        [ColumnName("kitchens"), LoadColumn(5)]
        public float Kitchens { get; set; }


        [ColumnName("link"), LoadColumn(6)]
        public string Link { get; set; }


        [ColumnName("zone"), LoadColumn(7)]
        public string Zone { get; set; }


        [ColumnName("price"), LoadColumn(8)]
        public float Price { get; set; }


    }
}
