// This file was auto-generated by ML.NET Model Builder. 

using Microsoft.ML;
using Microsoft.ML.Data;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace MLAPI.Services
{
    public interface IModelBuilder
    {
        IEstimator<ITransformer> BuildTrainingPipeline(MLContext mlContext);
        Task<string> CreateModel();
        string GetAbsolutePath(string relativePath);
        string RegressionFoldsAverageMetrics(IEnumerable<TrainCatalogBase.CrossValidationResult<RegressionMetrics>> crossValidationResults);
        ITransformer TrainModel(MLContext mlContext, IDataView trainingDataView, IEstimator<ITransformer> trainingPipeline);
    }
}