// This file was auto-generated by ML.NET Model Builder. 

using System;
using MLAPIML.Model;

namespace MLAPIML.ConsoleApp
{
    class Program
    {
        static void Main(string[] args)
        {
            // Create single instance of sample data from first line of dataset for model input
            ModelInput sampleData = new ModelInput()
            {
                Rooms = 1F,
                Area = 36F,
                Floor = 0F,
                Year = 2019F,
                Bathrooms = 1F,
                Kitchens = 1F,
                Zone = @"Aviatiei",
            };

            // Make a single prediction on the sample data and print results
            var predictionResult = ConsumeModel.Predict(sampleData);

            Console.WriteLine("Using model to make single prediction -- Comparing actual Price with predicted Price from sample data...\n\n");
            Console.WriteLine($"Rooms: {sampleData.Rooms}");
            Console.WriteLine($"Area: {sampleData.Area}");
            Console.WriteLine($"Floor: {sampleData.Floor}");
            Console.WriteLine($"Year: {sampleData.Year}");
            Console.WriteLine($"Bathrooms: {sampleData.Bathrooms}");
            Console.WriteLine($"Kitchens: {sampleData.Kitchens}");
            Console.WriteLine($"Zone: {sampleData.Zone}");
            Console.WriteLine($"\n\nPredicted Price: {predictionResult.Score}\n\n");
            Console.WriteLine("=============== End of process, hit any key to finish ===============");
            Console.ReadKey();
        }
    }
}
