// This file was auto-generated by ML.NET Model Builder. 

using System;
using MLAPIML.Model;

namespace MLAPIML.ConsoleApp
{
    class Program
    {
        static void Main(string[] args)
        {
            // Create single instance of sample data from first line of dataset for model input
            ModelInput sampleData = new ModelInput()
            {
                LotArea = 8450F,
                LotConfig = @"Inside",
                Zone = @"CollgCr",
                Floors = @"2Story",
                OverallCond = 5F,
                YearBuilt = 2003F,
                Rooms = 8F,
                SaleCondition = @"Normal",
            };

            // Make a single prediction on the sample data and print results
            var predictionResult = ConsumeModel.Predict(sampleData);

            Console.WriteLine("Using model to make single prediction -- Comparing actual SalePrice with predicted SalePrice from sample data...\n\n");
            Console.WriteLine($"LotArea: {sampleData.LotArea}");
            Console.WriteLine($"LotConfig: {sampleData.LotConfig}");
            Console.WriteLine($"Zone: {sampleData.Zone}");
            Console.WriteLine($"Floors: {sampleData.Floors}");
            Console.WriteLine($"OverallCond: {sampleData.OverallCond}");
            Console.WriteLine($"YearBuilt: {sampleData.YearBuilt}");
            Console.WriteLine($"Rooms: {sampleData.Rooms}");
            Console.WriteLine($"SaleCondition: {sampleData.SaleCondition}");
            Console.WriteLine($"\n\nPredicted SalePrice: {predictionResult.Score}\n\n");
            Console.WriteLine("=============== End of process, hit any key to finish ===============");
            Console.ReadKey();
        }
    }
}
